### ISSUE TITLE
Retry test case

### ISSUE THREAD

**Issue by bhenning10** [DMTF/SPDM-Responder-Validator#26]
I didn't see any test cases that test retry behavior. If there is a test case and I missed it, feel free to close this issue.
This should happen on a command like GET_DIGESTS so that it can ensure that the transcript hash is calculated correctly. It should just involve the Requester dropping the first response and then sending the same request again after waiting an appropriate time.

**Comment by jyao1** [comment]
The retry case is not there, because retry is an optional mechanism.

The test case will only test:
1) requirement for mandatory feature. (it must be implemented)
2) requirement for optional feature if it is implemented.

But there is no clue (capability) if the retry is implementation or not on device side.

Please let us know if there is any mandatory requirement for "retry".

**Comment by bhenning10** [comment]
Thanks for explaining the bounding criteria. I understand how you are trying to limit the tests, so we can close this issue.
